### ISSUE TITLE
"carousels" example doesn't work

### ISSUE THREAD

**Issue by dawkot** [karaxnim/karax#112]
When clicking on any button:
![image](https://user-images.githubusercontent.com/22991711/63903632-6edf6d80-ca0e-11e9-89e5-676e3e0fdd91.png)

I can't get VComponents to work with event handlers in general.

Nim 0.20.2, Karax@#head.

**Comment by greenfork** [comment]
I can confirm.

Nim devel, Karax head

![2019-09-07-200651_499x126_scrot](https://user-images.githubusercontent.com/20167110/64478056-55c38300-d1ab-11e9-8fe4-9df26a1c2375.png)

**Comment by dawkot** [comment]
Should've said it was introduced in https://github.com/pragmagic/karax/commit/e422087217ff3bbedfd23baaa2b2e713f47e3ecf
It works with the previous commit.

**Comment by timotheecour** [comment]
could that be related to https://github.com/pragmagic/karax/issues/56#issuecomment-531099826 ? (where I'm also observing that this commit introduces a regression in diffing)

**Comment by timotheecour** [comment]
still a problem with karun head, nim head d8fe79fa4041325da07892978336eb8a27e5ac6b

note: to reproduce:
`karun -r examples/carousel/carousel.nim`
