### ISSUE TITLE
input.value ignored when rendering on non-js target

### ISSUE THREAD

**Issue by dawkot** [karaxnim/karax#126]
### Example

```nim
import karax / [vdom, karaxdsl]

echo build_html input(class="foo", value="bar")
```

### Output

`<input class="foo"></input>`

### Expected Output

`<input class="foo" value="bar"></input>`

**Comment by zedeus** [comment]
Duplicate of #61

**Comment by dawkot** [comment]
> Duplicate of #61

I thought that one was just about `value` not being reactive

**Comment by ajusa** [comment]
Closing as it is a duplicate. https://github.com/karaxnim/karax/issues/61#issuecomment-520909139 is the specific comment where the server side rendering was brought up.
