### ISSUE TITLE
jjson's `%*` macro does not work with object variant types

### ISSUE THREAD

**Issue by nhanb** [karaxnim/karax#142]
On nim devel, karax 1.1.2
```nim
import karax / [jjson, kbase, kajax]

type
  RpcKind = enum
    doThis,
    doThat
  Rpc = object
    case kind: RpcKind
    of doThis: thisParam: kstring
    of doThat: thatParam: kstring

let obj = Rpc(kind: doThis, thisParam: "foo")
system.echo (%*obj).toJson
```

Expected: prints `{"kind": "doThis", "thisParam": "foo"}`
Got: compile error: ` expression cannot be cast to JsonNode=ref JsonNode:ObjectType`

While we're at it, I can get it to work by replacing karax utils with std's `json` module, specifically:

- `jjson.%*` -> `json.%*`
- `kajax.toJson` -> `json.$`
- `kstring` -> `string`

But I assume using karax's utils and kstring is more performant because that way it only works with native js strings and objects - is that correct?

**Comment by Araq** [comment]
>  is that correct?

Yes.

**Comment by ajusa** [comment]
This one can be solved similarly to https://github.com/karaxnim/karax/issues/104#issuecomment-830861588
Here's a working example using jsffi:
```nim
import karax / [kbase, kajax]
include karax/prelude
import jsffi
type
  RpcKind = enum
    doThis,
    doThat
  Rpc = object
    case kind: RpcKind
    of doThis: thisParam: kstring
    of doThat: thatParam: kstring

let obj = Rpc(kind: doThis, thisParam: "foo")
let objJs = obj.toJS
let original = objJs.to(Rpc)
kout objJs
kout original
kout original.thisParam
```
Output:
```js
{kind: 0, thisParam: "foo", thatParam: null}
{kind: 0, thisParam: "foo", thatParam: null}
foo
```
Again, I think jsffi is just as performant as the jjson module, so I would recommend using it over jjson as jsffi is part of the stdlib.
(If you want to turn this into a string, you can use https://github.com/karaxnim/karax/blob/master/karax/kajax.nim#L130)

Please reopen if you have any other issues!
