### ISSUE TITLE
kajax documentation / examples

### ISSUE THREAD

**Issue by sdmcallister** [karaxnim/karax#165]
Would be nice to have simple examples for Kajax and possibly with Jester.  Kajax, I assume, is used often in a SPA so I think it is worth adding especially for people  who are learning how to create SPA (and with Nim).  Some examples may include an authentication example, or populating a view from data in a db like sqlite.

**Comment by ajusa** [comment]
Here's an example that I put together: https://github.com/ajusa/simple-twitter
Uses kajax to fetch data from Jester using a sqlite DB, which seems to fit what you asked for :smile: 
Currently the only example within Karax itself is https://github.com/karaxnim/karax/blob/master/experiments/ajaxtest.nim, which is a simple GET request.

Please reopen if you have further questions! Kajax will probably be better documented once Karax is, hopefully that happens soon. Also, see https://github.com/nim-lang/Nim/pull/17373 for a PR that might end up replacing/extending Kajax, as then the stdlib will have a way to do HTTP requests from JS.
