### ISSUE TITLE
XHR: Failed Loading (Kajax)

### ISSUE THREAD

**Issue by sdmcallister** [karaxnim/karax#172]
Just wondering if failed loading is expected given the code below or if there is some idiomatic/alternative way to use ajax for authentication.

I'm using jester for the server and it responds with a 200 OK as expected. 

```
import karax / [vdom, karax, karaxdsl, kajax]
import json

var isloggedin = false

proc login() =
  var j = newJObject()
  j["email"] = ($getVNodeById("email").getInputText).newJString()
  j["password"] = ($getVNodeById("password").getInputText).newJString()
  proc cb(stat: int, resp: cstring) =
    if stat == 200:
      echo "Success"
      isloggedin = true
  ajaxPost("http://localhost:5000/login", @[], $j, cb)

proc createDom(): VNode =
  result = buildHtml(tdiv):
    if not isloggedin:
      section:
       h3: text "Login Form"
      section:
        form:
          label(`for`="input1"): text "Email"
          input(`class` = "input", `autocomplete`= "username",id = "email")
          label(`for`="input2"): text "Password"
          input(`class` = "input", id = "password",`autocomplete`="current-password",`type`="password", onkeyupenter = login)
          button(onClick = login): text "Submit"
    else:
      tdiv:
        text "You are Logged In"

setRenderer createDom
```

**Comment by ajusa** [comment]
Could you provide more details here? This looks correct to me, however you may be running into [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) when you try and make a request to the Jester backend. If you are running the Karax code using `karun`, then it will be on a different port, and so a different domain than the Jester server. The browser would then prevent the connection from going through as a security policy. If you are running into a CORS errors, you may need to try proxying, disabling CORS for development purposes in your browser, or serving the Karax frontend from Jester itself, as a static file.

If you could provide a screenshot/error message that would be very helpful in further tracking down the issue!

**Comment by sdmcallister** [comment]
@ajusa Yes, I think that was the problem.
