### ISSUE TITLE
`checked` doesn't get updated

### ISSUE THREAD

**Issue by dawidkotlin** [karaxnim/karax#186]
### Description
Checkboxes don't become checked/unchecked when expected

### Workaround
Changing input's `id` on every redraw

### Example
1) click checkbox at least one
2) from now on, pressing the button won't update the checkbox value
```nim
include karax/prelude

var
  b: bool

setRenderer proc: VNode =
  echo b
  buildHtml tdiv:
    p:
      text"Checkbox"
      input(`type`="checkbox", checked=toChecked(b)):
        proc onChange =
          b = not b
    p:
      button:
        text"Button"
        proc onClick =
          b = not b
```
### Details
Karax 1.2.1
Nim 1.4.2

**Comment by ajusa** [comment]
Note that this is similar to https://github.com/karaxnim/karax/issues/61 and probably also has the exact same root cause.
