### ISSUE TITLE
Css variables

### ISSUE THREAD

**Issue by thisago** [karaxnim/karax#191]
How I can set the CSS variables in style using `buildHtml` macro?

**Comment by ajusa** [comment]
I assume you are talking about https://caniuse.com/css-variables
For those, Karax doesn't have any special code to handle them. You can use the stdlib (specifically `kdom` from Karax which imports `dom` from the stdlib) modules like this to set the value for one:
```nim
include karax/prelude
import karax/[vstyles, kdom]
document.documentElement.style.setProperty(kstring"--my-color", kstring"pink")
echo document.documentElement.style.getPropertyValue(kstring"--my-color")
proc render(): VNode =
  buildHtml(tdiv):
    p(style = style((StyleAttr.color, kstring"var(--my-color)"))):
      text "asdf"
setRenderer render
```
Please correct me/reopen if I misunderstood your question! I wasn't super sure what you were asking about.
