### ISSUE TITLE
Strange edge case with onblur not causing an update

### ISSUE THREAD

**Issue by ajusa** [karaxnim/karax#192]
MWE:
```nim
include karax / prelude
import karax/kdom
var show = true
var newInput = false
proc createDom(): VNode =
  result = buildHtml(tdiv):
    if show:
      input():
        proc onblur() =
          show = false
          echo "blurred"
        proc onkeydown(e: Event, n: VNode) =
          let key = (KeyboardEvent) e
          if key.keyCode == 9 and not key.shiftKey: #tab
            e.preventDefault()
            newInput = true
      if newInput:
        input(setFocus = true):
          proc oninput() =
            echo "test"
setRenderer createDom
```
What happens: Focus on the input, hit tab, and then after typing a single letter both inputs vanish
Expected: Focus on the input, hit tab, both inputs vanish
When I ran it, I noticed that the "blurred" is printed to the console as soon as I hit tab. So, show = false, but Karax doesn't seem to actually update/diff the dom until I enter in a new keypress, which triggers the next redraw.

hotdog on Discord came up with this workaround:
```nim
include karax/prelude
import karax/kdom

var show = true
var newInput = false

proc createDom: VNode =
  result = buildHtml(tdiv):
    if show:  
      input(id="input1"):
        proc onblur = 
          show = false 
          echo "blurred"
          discard window.requestAnimationFrame(proc(_: float) = redraw())

        proc onkeydown(e: Event, n: VNode) =
          let key = e.KeyboardEvent
          if key.keyCode == 9 and not key.shiftKey:
            e.preventDefault()
            newInput = true

    if newInput:
      input(setFocus = true, id="input2"):
        proc oninput =
          echo "test" 

setRenderer createDom
``` 
which works, but it requires called redraw on the next frame for some reason, calling redraw manually doesn't work (as Karax called redraw after every event anyway).

**Comment by geotre** [comment]
The issue is that the two events fire very close together:

```
1. "onkeydown" fires
2. "redraw" is called, it queues up "dodraw" to run
3. "dodraw" starts rerendering
4. "onblur" fires
5. "redraw" is called, but it does *not* queue up dodraw, as the diffing/rerendering is still happening 
6. "dodraw" finishes the rerender
```

The result being that Karax renders the changes from the `onkeydown` callback only.

Karax uses `kxi.renderId` to prevent adding multiple `dodraw` calls to the queue, but it also uses the renderId to stop `dodraw` being queued while a render is happening. I think this needs to be changed so that:

* `dodraw` cannot be queued multiple times
* If `dodraw` fires while it is already running, simply queue another `dodraw` and return

PR incoming.
