### ISSUE TITLE
bulma icon

### ISSUE THREAD

**Issue by mantielero** [karaxnim/karax#209]
I am trying to show an icon with bulma. That is done with:
```html
<span class="icon">
  <i class="fas fa-home"></i>
</span>
```
With karax:
```nim
span(class="icon"):
  i(class="fas fa-home")
```
gives the error: 
```
Error: undeclared identifier: 'i'
```

Is there anything that I could do about it?

**Comment by ajusa** [comment]
Some of the shorter tag names are different from their HTML counterparts, similar to `tdiv`. For `<i>` we use `italic` instead. See https://github.com/karaxnim/karax/blob/master/karax/vdom.nim#L34 for the mapping.

Your example should become
```nim
span(class="icon"):
  italic(class="fas fa-home")
```

**Comment by mantielero** [comment]
Thanks a lot.
