### ISSUE TITLE
htmx not getting data.

### ISSUE THREAD

**Issue by sdmcallister** [karaxnim/karax#212]
It appears that loadscript seems to solve the issue describe more below but I'm submitting anyway. I assumed that placing htmx in the html head would be sufficient but nothing happens and there are no errors.  Other libraries like vega-lite don't require using loadscript (maybe I should be?)  It appears that on the nim forum others use htmx so it surprised me that I couldn't get this working initially using the code below.  

My karax file:
```
include karax / prelude

proc render(): VNode =
  buildHtml(tdiv):
    tdiv(id="parent-div"): text "basic"
    button(hx-get="/somedata",
        hx-trigger="click",
        hx-target="#parent-div",
        hx-swap="outerHTML"): text "Click for data"

setRenderer render 
```
My Jester File:

```
import jester

const indexHtml = """
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
  </head>

  <body id="body">
    <div id="ROOT" />
    <script type="text/javascript" src="/app.js"></script>
  </body>
</html>
""" 

routes:
  get "/":
    resp indexHtml
  get "/somedata":
    resp Http200, {"Content-Type": "text/html"}, "<h3>You got the data</h3>" 
```

What did work was this (and I didn't need to add the script to the const in the jester file):

```
include karax / prelude


proc render(): VNode =
  
  buildHtml(tdiv):
    tdiv(id="parent-div"): text "basic"
    button(hx-get="/somedata",
        hx-trigger="click",
        hx-target="#parent-div",
        hx-swap="outerHTML"): text "Click for data"

setRenderer render 
loadScript("https://unpkg.com/htmx.org@1.5.0")
```

**Comment by ajusa** [comment]
I *think* what might be happening in the first case is that the htmx script is loaded and ran (looking for all of the `hx-` attributes) before Karax loads in. So all it would see is the 
```html
<body id="body">
    <div id="ROOT" />
    <script type="text/javascript" src="/app.js"></script>
  </body>
  ```
  On the other hand, loading the script in Karax means that htmx only runs after Karax has finished rendering the dom, which means that the elements exist before the script is loaded.

**Comment by sdmcallister** [comment]
@ajusa  Thank you.
