### ISSUE TITLE
Update the package structure for Nimble

### ISSUE THREAD

**Issue by WeebNetsu** [karaxnim/karax#219]
After installing this with Nimble we get this warning:
```
Warning: Package 'karax' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'karax', but file 'widgets.nim' is in a directory named 'experiments/trello' instead. This will be an error in the future.

Hint: If 'experiments/trello' contains source files for building 'karax', rename it to 'karax'. Otherwise, prevent its installation by adding `skipDirs = @["experiments/trello"]` to the .nimble file.
```

Seems like this will become an error in the future

OS: Arch Linux
Nim: 1.6.0
Nimble: 0.13.1

**Comment by geotre** [comment]
From what I understand there are no actual plans to deprecate this kind of structure in nimble any time soon. If this becomes a problem we will adjust the package.

Closing this issue for now. Please feel free to re-open and comment if you want to discuss further.
