### ISSUE TITLE
Delay in redrawing dom

### ISSUE THREAD

**Issue by C-NERD** [karaxnim/karax#227]
I am using karax in the frontend in a reactive manner and i need to display a toast after making a request but for some reason when i call the setToast proc from an onclick listener it takes 2 clicks to update the dom even after i called markDirty on the variable for the toast Object (ref of Vcomponet).
Here is the toast type
```nim
type

    Display {.pure.} = enum

        None = "none"
        Flex = "flex"

    Toast = ref object of VComponent

        display : Display
        msg : string
        timems : int
        timer : TimeOut
```
Here is the proc called by the onclick listener
```nim
        proc register() {.closure.} =
                
            let
                password_vnode = getVNodeById("password")
                retypepassword_vnode = getVNodeById("password")

            if password_vnode.getInputText() != retypepassword_vnode.getInputText():

                setToast("Passwords do not match")

                password_vnode.style = style(borderRadius, "2px solid red")
                retypepassword_vnode.style = style(borderRadius, "2px solid red")
                return

            var body : JsonNode = newJObject()
            let
                username = getVNodeById("username").getInputText()
                email = getVNodeById("email").getInputText()

            body["username"] = toJson(username)
            body["email"] = toJson(email)
            body["password"] = toJson(password_vnode.getInputText())
            callBackendJson[ErrorCode]("/register.json", ($body).cstring, Put, 10000):

                if data.status:

                    clearOverlay()

                setToast(data.msg)
```
Here is the setToast proc which handles the actual toast redraw
```nim
proc setToast(msg : string, timems : int = 2500) =

    generaltoast.markDirty()
    if not generaltoast.timer.isNil():

        generaltoast.timer.clearTimeout()
        generaltoast.timer = nil

    generaltoast.display = Display.Flex
    generaltoast.msg = msg
    generaltoast.timems = timems
    
    generaltoast.timer = runLater(
        
        () => (generaltoast.markDirty(); generaltoast.display = Display.None; generaltoast.msg = ""; generaltoast.timer = nil),
        generaltoast.timems
    )
```
Any answer is appreciated

**Comment by C-NERD** [comment]
> Can you share a minimal reproducible example?

I just created a minimal example and the example works fine. So I tried debugging my code and I found out that the delay only occurs when I try to call setToast after making a request. I don't think I will be able to created a minimal reproducible example but I can send the file. It's about 300 lines of code

**Comment by geotre** [comment]
Yeah share it. Are you using the request procs from karax or something else? Depending on how your request code works you may just need to call `redraw` once the request returns

**Comment by C-NERD** [comment]
Sorry for the late reply. Here is a link to a google drive folder containing the files https://drive.google.com/drive/folders/1ELUzC0cGzfEmDqHI21vquvrWkogMizJH?usp=sharing the files include utils.nim which implements most of the code, homepage.nim the file which imports from utils.nim to make the home page and views.tmpl which contains code that the application uses for calling apis. The setToast code is inside utils.nim

**Comment by geotre** [comment]
Your `fetchWithTimeOut` code needs to call [Karax's redraw proc](https://github.com/karaxnim/karax/blob/aab6357cd5b6c7c9588e0097616a5a2a339e7f37/karax/karax.nim#L695) after the request has returned. You can see how it is done in [Karax's own request procs](https://github.com/karaxnim/karax/blob/aab6357cd5b6c7c9588e0097616a5a2a339e7f37/karax/kajax.nim#L77).

This is not a bug, this is just how Karax implements reactivity (by redrawing on events)

**Comment by C-NERD** [comment]
Thanks 👍 that worked, but I didn't add redraw in the `fetchWithTimeOut` function but inside the setToast proc (adding that detail just Incase anybody else is reading this)
