### ISSUE TITLE
Boolean Attributes in DSL

### ISSUE THREAD

**Issue by ryukoposting** [karaxnim/karax#239]
Karax's DSL doesn't handle "value-less" attributes well.

Consider the case where I need an input to either be enabled or disabled based on the value of a boolean. Right now, I have to do something like this:

```nim
proc drawButton(isInvalid: bool): VNode =
  buildHtml(tdiv):
    if isInvalid:
      button(disabled=""): text "My Button"
    else:
      button(): text "My Button"
```

It would be much more intuitive if I could just do this:

```nim
proc drawButton2(isInvalid: bool): VNode =
  buildHtml(tdiv):
    button(disabled=isInvalid): text "My Button"
```

On both the C and JS backends, `drawButton2` gives this error:

```
.../app.nim(73, 12) Error: type mismatch: got <VNode, string, bool>
but expected one of:
proc setAttr(n: VNode; key: kstring; val: kstring = "")
  first type mismatch at position: 3
  required type for val: kstring
  but expression 'isValid' is of type: bool
```

I'm going to doodle a solution to this, but I'd like to hear thoughts from the community.

**Comment by geotre** [comment]
Karax has solutions for this, see toChecked/toDisabled/toSelected here https://github.com/karaxnim/karax/blob/32c6139db04905ab2596e66846cd5911b461939d/karax/karax.nim#L850On 19 Feb 2023, at 17:58, ryukoposting ***@***.***> wrote:﻿
Karax's DSL doesn't handle "value-less" attributes well.
Consider the case where I need an input to either be enabled or disabled based on the value of a boolean. Right now, I have to do something like this:
proc drawButton(isInvalid: bool): VNode =
  buildHtml(tdiv):
    if isInvalid:
      button(disabled=""): text "My Button"
    else:
      button(): text "My Button"
It would be much more intuitive if I could just do this:
proc drawButton2(isInvalid: bool): VNode =
  buildHtml(tdiv):
    button(disabled=isInvalid): text "My Button"
On both the C and JS backends, drawButton2 gives this error:
.../app.nim(73, 12) Error: type mismatch: got <VNode, string, bool>
but expected one of:
proc setAttr(n: VNode; key: kstring; val: kstring = "")
  first type mismatch at position: 3
  required type for val: kstring
  but expression 'isValid' is of type: bool

I'm going to doodle a solution to this, but I'd like to hear thoughts from the community.

**Comment by ryukoposting** [comment]
Some documentation on how these are used would be helpful.

**Comment by geotre** [comment]
You pass a boolean, e.g. 
```nim
let
  completed1 = false
  completed2 = true
  buttonDisabled = true

  colors = [
    "red".cstring,
    "green",
    "blue"
  ]
  selectedColor = colors[1]

buildHtml(tdiv):
  input(`type` = "checkbox", checked = toChecked(completed1))
  input(`type` = "checkbox", checked = toChecked(completed2))
  button(disabled = toDisabled(buttonDisabled))
  select:
    for color in colors:
      option(value=color, selected=toSelected(color == selectedColor)):
        text color
```
```html
<input type="checkbox" />
<input type="checkbox" checked="checked" />
<button disabled="disabled"></button>
<select>
  <option value="red">red</option>
  <option value="green" selected="selected">green</option>
  <option value="blue">blue</option>
</select>
```

**Comment by ryukoposting** [comment]
Does this approach support all boolean-like attributes, including `contenteditable`?

**Comment by geotre** [comment]
It does. Maybe a broader name (like "toAttr") would make sense here for all the boolean attributes that aren't disabled/checked/selected

**Comment by geotre** [comment]
All merged
