### ISSUE TITLE
Release 1.2.3

### ISSUE THREAD

**Issue by geotre** [karaxnim/karax#242]
Can we tag v1.2.3? `nimble install karax` still installs 1.2.2 which does not contain the fixes from #234

**Comment by geotre** [comment]
@Araq would you be open to adding me as a maintainer so I can create new releases and clean up the issue backlog a bit?

**Comment by pietroppeter** [comment]
thanks for the great help you are doing here on maintaining karax, maybe even @ringabout has the rights to do that?

**Comment by ringabout** [comment]
No, I don't have access.

**Comment by ringabout** [comment]
done https://github.com/karaxnim/karax/releases/tag/1.2.3
