### ISSUE TITLE
view doesn't update when changing state in setInterval

### ISSUE THREAD

**Issue by Athlon64** [karaxnim/karax#243]
Minimal code as follows:

```
include karax/prelude
import karax/kdom

var v = 10
proc update() =
  v += 10
  # redraw()
discard setInterval(update, 200)

proc main(): VNode =
  result = buildHtml(tdiv):
    text $v

setRenderer main
```
The view won't get update unless calling _redraw()_ explicitly.

**Comment by geotre** [comment]
This is expected. Karax's reactivity model is different to mainstream frameworks (like React and Vue). They implement it by creating reactive state with useState/setState etc. Karax instead reacts to events, similar to things like Elm.

This approach is perhaps simpler and easier to reason about, with the tradeoff being that events need to be wrapped to trigger a redraw. Karax does this for you with [dom event handlers](https://github.com/karaxnim/karax/blob/32c6139db04905ab2596e66846cd5911b461939d/karax/karax.nim#L782), [ajax network calls](https://github.com/karaxnim/karax/blob/32c6139db04905ab2596e66846cd5911b461939d/karax/kajax.nim#L77), etc, but you will need to add it for things outside of that (websocket messages, document timing functions).

So the recommended solution would be something like:

```nim
include karax/prelude
import karax/kdom except setInterval

proc setInterval(cb: proc(), interval: int): Interval =
  kdom.setInterval(proc =
    cb()
    if not kxi.surpressRedraws: redraw(kxi)
  , interval)

var v = 10
proc update() =
  v += 10
discard setInterval(update, 200)

proc main(): VNode =
  result = buildHtml(tdiv):
    text $v

setRenderer main
```

Does that all make sense?

**Comment by Athlon64** [comment]
I got it. Many thanks, @geotre, your explanation is crystal clear.
By the way, I really think we should put this in the document.

**Comment by geotre** [comment]
Thanks for the suggestion @Athlon64, I have added it!
