### ISSUE TITLE
runtime error on redraw in `removeAllEventHandlers` proc

### ISSUE THREAD

**Issue by choltreppe** [karaxnim/karax#275]
So sometimes I get a runtime error on redraw:
```
Uncaught TypeError: d_1409286269 is null
    removeAllEventHandlers_1409286268
...
```
I fixed it in my local `.nimble/pkgs2/` copy like this:
```nim
proc removeAllEventHandlers(d: Node) =
  if d != nil and d.karaxEvents != nil:
    for i in 0..<d.karaxEvents.len:
      d.removeEventListener(d.karaxEvents[i][0], d.karaxEvents[i][1])
```
but Im not sure if thats a real fix, or just fixing the symptoms

**Comment by geotre** [comment]
Are you able to narrow it down to a simple reproducible example? I suspect it’s an issue attaching event listeners to certain node types but I haven’t looked into it yet
