### ISSUE TITLE
setDragImage type signature causing BigInt conversion issue

### ISSUE THREAD

**Issue by chancyk** [karaxnim/karax#284]
Any idea why the signature for setDragIamge uses int64? It exists in both the Nim dom module and kdom_impl here.

https://github.com/nim-lang/Nim/blob/78c834dd76f273d8813247647531005a1f7db1a6/lib/js/dom.nim#L1658
https://github.com/karaxnim/karax/blob/141f116535f6a16de17f426b9d09294aa28486e6/karax/kdom_impl.nim#L1160

It seems to be causing this error in the browser:  `Uncaught TypeError: Cannot convert a BigInt value to a number`
Due to emitting `0n` instead of `0`:  `dev_704645398.dataTransfer.setDragImage(overlay_704645399, 0n, 0n);`

Converting it to `int` seems to solve the issue for me.

**Comment by Araq** [comment]
Good point, please fix it.

**Comment by ringabout** [comment]
fixed by https://github.com/karaxnim/karax/pull/286
