### ISSUE TITLE
Graph without explanation

### ISSUE THREAD

**Issue by PMunch** [karaxnim/karax#5]
The graph showing performance comparison should really have some kind of explanation with it. Specifically the colours aren't documented anywhere and makes the whole thing rather confusing..

**Comment by vladyio** [comment]
Besides, notice "Elm 0.17" is shown twice for some reason.

**Comment by PMunch** [comment]
Angular 2 as well, the pink bars are separate from the blue ones, but it's not described which is which..

**Comment by ajusa** [comment]
Closing this since the graph isn't mentioned in the README anymore, and because the issue is over 4 years old.
