### ISSUE TITLE
The callback to ajax can give a status of ``0`` due to xhr

### ISSUE THREAD

**Issue by dom96** [karaxnim/karax#57]
This case should be handled, see here https://stackoverflow.com/questions/36416389/why-does-my-xmlhttprequest-have-readystate-4-but-status-0

**Comment by ajusa** [comment]
How should it be handled though? A status of 0 just means a (client-side) error, and according to that StackOverflow post the easiest way to figure out what the error was is to look at the JS console and see what it says.

**Comment by geotre** [comment]
From a quick look at the thread, it seems like the best option might be to add an `onerror` handler to the call that throws an exception.

**Comment by geotre** [comment]
I've investigated this a bit more, and it seems there is no way to get details of the error from `onerror` so it is a bit useless. If you need to handle this case just check `status == 0` in your callback.

If you have any other suggestions for how to approach this better please reopen the issue
