### ISSUE TITLE
Setting `value` of an `input` doesn't seem to work

### ISSUE THREAD

**Issue by dom96** [karaxnim/karax#61]

**Comment by citycide** [comment]
I just ran into this, `value` doesn't seem to be reactive.

**Comment by Araq** [comment]
Depends on how you set it. ``setInputText`` works.

**Comment by Araq** [comment]
@citycide Please try to give the elements an ``id`` attribute as a workaround so that the diff algorithm doesn't "optimize" this.

**Comment by zedeus** [comment]
This doesn't work for server-side rendering either.

```nim
import karax/[karaxdsl, vdom]
echo buildHtml(input(`type`="text", value="test"))
echo buildHtml(input(`type`="text", value="test", id="test", placeholder="test"))
```

Output:
```html
<input type="text"></input>
<input id="test" type="text" placeholder="test"></input>
```

**Comment by gogolxdong** [comment]
```nim
import karax / [vdom, karaxdsl, karax, jstrutils]

var value = 1          
proc createDom(): VNode =
    buildHtml(tdiv):
        kout value
        input(id="accessType", value= $value): text $value
        button(onclick = proc(e:Event, n:VNode) = 
            value.inc
            ): text "change"
   
setRenderer createDom
```
value and text both don't work.

**Comment by kidandcat** [comment]
bump, this still has no solution

**Comment by nhanb** [comment]
Looks like commit f6bda9a didn't fix it. I can reproduce the bug with this snippet (cleaned up @gogolxdong's to compile correctly):

```nim
import karax / [vdom, karaxdsl, karax, jstrutils]

var v = 1

proc createDom(): VNode =
  buildHtml(tdiv):
    kout v
    input(id="myid",  placeholder = $v, value = $v)
    button(onclick = proc(e:Event, n:VNode) =
      v.inc
    ): text "change"

setRenderer createDom
```
Using karax 1.1.2 & nim devel.

**Comment by ajusa** [comment]
I can also reproduce on Karax 1.2.1. Not super sure what the best option is here, as it seems that Karax doesn't think that the value has changed so the dom isn't redrawn correctly? Like if I do this
```nim
import karax / [kdom, vdom, karaxdsl, karax, jstrutils]
var v = 1
proc createDom(): VNode =
  buildHtml(tdiv):
    kout v
    input(id= $v, placeholder = $v, value = $v)
    button(onclick = proc(e:Event, n:VNode) =
      v.inc
    ): text "change"

setRenderer createDom
``` 
everything works fine, because the id changes so Karax knows to update the dom.

**Comment by jyapayne** [comment]
@ajusa this is actually an issue with HTML itself. For an input tag, `value` is only used once on page render. If you update the value property in regular JS, the same behavior can be observed, which is why you need something like my PR to update the dom value as well. Same goes for the `checked` property.
