### ISSUE TITLE
Consider making it a warning/error to set `onchange` on an `input`

### ISSUE THREAD

**Issue by dom96** [karaxnim/karax#62]
`onchange` is superseeded by `oninput`. `onchange` is pretty much useless.

https://stackoverflow.com/a/26202266/492186

**Comment by geotre** [comment]
This would be definitely be useful, but I feel there are many situations where attributes can be deprecated, ineffective, or outright ignored. If we go this route of adding warnings to Karax I think it should be more comprehensive and cover more ground. React for example will create warnings for many different things - css styles, attributes, child elements, etc.

I'm going to close for now as there is no recent progress and the fix may be quite involved. Please feel free to re-open and comment if you want to continue the discussion!
