### ISSUE TITLE
Can we have a static version of kxi?

### ISSUE THREAD

**Issue by gogolxdong** [karaxnim/karax#93]
Karax is designed for Web APP, though it has some basice support for static website. I was wondering whether we have a chance to have something like
```nim
proc `$`(k: karaxInstance): kstring
```
so that the static webiste generating from Karax become seamless.

**Comment by kidandcat** [comment]
this looks like a duplicate of #90

**Comment by ajusa** [comment]
Yeah, I think this can be closed with https://github.com/karaxnim/karax/pull/162 now.
