### ISSUE TITLE
Removing list item redraws list with wrong elements

### ISSUE THREAD

**Issue by hiteshjasani** [karaxnim/karax#98]
I'm having an issue in my own code where removing elements from a list removes the wrong element.  But I haven't understood the problem well enough to create a separate test case.

So I started playing around with https://github.com/pragmagic/karax/blob/devel/tests/components.nim to see if I was using Karax wrong and I found a bug that might be related to mine.

**To reproduce:**

1. Load https://github.com/pragmagic/karax/blob/devel/tests/components.nim in a JS app
2. It should display textfields with the following: "Karax", "Abathur", "Fenix" and blank
3. Click the '(X)' after "Abathur"

**Expected:**

1. Textfields with "Karax", "Fenix" and blank should be displayed
2. The JS console should show a seq of @["Karax", "Fenix"]

**Actual:**

1. Textfields with "Karax", "Abathur" and blank are displayed. <-- this is wrong!
2. The JS console shows a seq of @["Karax", "Fenix"]

**Comment by kidandcat** [comment]
https://forum.nim-lang.org/t/4857

**Comment by kidandcat** [comment]
I'm pasting forum solution here. Close issue if resolved, thanks.

> Your problem is that when you sort your <li> elements Karax can't properly follow their location, because for it, they are just <li> elements without anything to compare them, so Karax doesn't know which <li> must be removed. In react it is solved by adding a unique "key" prop, but I think Karax doesn't say much about that.
> 
> To allow Karax know what to remove, just add "x" as an id to <li> element:

```nim
ul:
      for x in people:
        li(id=x):
          text x
          span:
            button(`type` = "button", onclick = mkRemoveAction(x)):
              text "(X)"
```

**Comment by Araq** [comment]
Components are the wrong idea, the virtual DOM is stateless. The much better idea is keep the state in the real DOM and tell Karax to use these nodes directly, see https://github.com/pragmagic/karax/blob/master/experiments/nativenodes.nim for an exampe.

**Comment by ajusa** [comment]
Closing issue now, use `id` so that the vdom knows that the element itself has changed and can diff properly. Reopen if you have further questions!
