### ISSUE TITLE
How to fix hot load script VNode ?

### ISSUE THREAD

**Issue by gogolxdong** [karaxnim/karax#99]
```nim
proc createDom(data: RouterData): VNode =
  buildHtml tdiv:
    if getItem("cloudfastLoggedIn") != "1":
      loginView({"":""}.toTable)
      script(src="dxcaptcha.js")
    else:
      layout()
      script(src="layuiAnimation.js")
```
shows after login, the script structure remains the old instead of switching , window.location.reload() is the only workaround and cause a consequensial flash.

**Comment by kidandcat** [comment]
Put an ID on the script tags:

```
proc createDom(data: RouterData): VNode =
  buildHtml tdiv:
    if getItem("cloudfastLoggedIn") != "1":
      loginView({"":""}.toTable)
      script(src="dxcaptcha.js", id="one")
    else:
      layout()
      script(src="layuiAnimation.js", id="two")
```

**Comment by gogolxdong** [comment]
Thanks, works for now, how do you solve the script loading and unloading problem?

**Comment by kidandcat** [comment]
It is not related to karax nor DOM. Once you load an script in the browser, you cannot stop that code's execution by any means (well, ofc you can reload the webpage). 

The script itself should be responsible of its own "shutdown" by removing the listeners it setup and stopping timers it manages.

**Comment by gogolxdong** [comment]
In some other non-VDOM framework  , the script at bottom only works after the page loading. I want to know whether tagging script node with id is a best practice , does it have problems even handling listener and timer properly,  will this handling be interleaved or error prone at last?

**Comment by kidandcat** [comment]
The id on the scripts is only for Karax to identify them as different elements an trigger an update. It's to solve the same here: https://github.com/pragmagic/karax/issues/98

You must code the handling of listeners and timers part, karax doesn't manage that (no framework manages that)

**Comment by ajusa** [comment]
I believe that this can be closed, reopen if you have further questions!
